let n9 = document.getElementById("btn9")
let n8 = document.getElementById("btn8")
let n7 = document.getElementById("btn7")
let n6 = document.getElementById("btn6")
let n5 = document.getElementById("btn5")
let n4 = document.getElementById("btn4")
let n3 = document.getElementById("btn3")
let n2 = document.getElementById("btn2")
let n1 = document.getElementById("btn1")
let n0 = document.getElementById("btn0")
var resultado = document.getElementById("resultado")

const soma = document.getElementById("btnSoma")
const multiplicacao = document.getElementById("btnMultiplicacao")
const divisao = document.getElementById("btnDivisao")
const subtracao = document.getElementById("btnSubtracao")
const igual = document.getElementById("btnIgual")
const limpar = document.getElementById("btnClear")
